//
//  LandingViewController.swift
//  Clean Swift Base
//
//  Created by Oriol on 10/2/17.
//  Copyright (c) 2017 Oriol. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol LandingViewControllerInput {
    
}

protocol LandingViewControllerOutput {
    
}

class LandingViewController: UIViewController, LandingViewControllerInput {
    
    var output: LandingViewControllerOutput!
    var router: LandingRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        LandingConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Event handling
    
    
    // MARK: Display logic
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension LandingViewController: LandingPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue)
    }
}
