//
//  LandingModels.swift
//  Clean Swift Base
//
//  Created by Oriol on 10/2/17.
//  Copyright (c) 2017 Oriol. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit



struct LandingScene {
    struct NavigateToNextScene {
        
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
