//
//  LandingRouter.swift
//  Clean Swift Base
//
//  Created by Oriol on 10/2/17.
//  Copyright (c) 2017 Oriol. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol LandingRouterInput {
    
}

protocol LandingRouterDataSource:class {
    
}

protocol LandingRouterDataDestination:class {
    
}

class LandingRouter: LandingRouterInput {
    
    weak var viewController:LandingViewController?
    weak private var dataSource:LandingRouterDataSource?
    weak var dataDestination:LandingRouterDataDestination?
    
    struct SegueIdentifiers {
        
    }
    
    init(viewController:LandingViewController, dataSource:LandingRouterDataSource, dataDestination:LandingRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(_ segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
