//
//  LandingPresenter.swift
//  Clean Swift Base
//
//  Created by Oriol on 10/2/17.
//  Copyright (c) 2017 Oriol. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol LandingPresenterInput {
    
}

protocol LandingPresenterOutput: class {
    
}

class LandingPresenter: LandingPresenterInput {
    
    weak var output: LandingPresenterOutput!
    
    // MARK: Presentation logic
    
}
