//
//  LandingInteractor.swift
//  Clean Swift Base
//
//  Created by Oriol on 10/2/17.
//  Copyright (c) 2017 Oriol. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol LandingInteractorInput {

}

protocol LandingInteractorOutput {
    
}

protocol LandingDataSource {
    
}

protocol LandingDataDestination {
    
}

class LandingInteractor: LandingInteractorInput, LandingDataSource, LandingDataDestination {
    
    var output: LandingInteractorOutput?
    
    // MARK: Business logic
}
